language: ruby
rvm:
  - 2.0.0

bundler_args: --path=vendor/bundle --without heroku

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - sh -c "psql -c 'create database ffcrm_mailchimp_development;' -U postgres"
  - sh -c "psql -c 'create database ffcrm_mailchimp_test;' -U postgres"
